const foodDatabase = [
    // --- MIS PLATILLOS / FAVORITOS ---
    {
        name: "Rol de Canela Glaseado (Pieza Grande 300g)",
        category: "Others",
        icon: "fa-cookie-bite",
        cal: 1080, fat: 40, prot: 14, carb: 140, purines: 15,
        status: "caution",
        tip: "CUIDADO CON EL AZÚCAR. Tiene pocas purinas \"directas\", pero 140g de carbohidratos (azúcar refinada) dispararán tu ácido úrico endógeno. Además, la levadura de panadería contiene algunas purinas. Cómelo compartido, nunca entero.",
        favourite: true,
        ingredients: [
            { name: "Harina de trigo", amount: "150g" },
            { name: "Mantequilla", amount: "60g" },
            { name: "Azúcar morena", amount: "80g" },
            { name: "Canela en polvo", amount: "2 cdas" },
            { name: "Huevo", amount: "1 pieza" },
            { name: "Leche", amount: "50ml" },
            { name: "Levadura", amount: "10g" },
            { name: "Glaseado de azúcar", amount: "40g" }
        ]
    },
    {
        name: "Cereal con Leche y Fruta (Tazón)",
        category: "Others",
        icon: "fa-bowl-food",
        cal: 280, fat: 6, prot: 10, carb: 45, purines: 15,
        status: "safe",
        tip: "BUENA OPCIÓN. La mayoría de los cereales y la leche son seguros para el ácido úrico (especialmente si es descremada). Añadir fruta fresca (fresas/plátano) aporta Vitamina C, que ayuda a reducir niveles de ácido úrico.",
        favourite: true,
        ingredients: [
            { name: "Cereal integral", amount: "40g" },
            { name: "Leche semidescremada", amount: "200ml" },
            { name: "Fresas", amount: "5 piezas" },
            { name: "Plátano", amount: "1/2 pieza" },
            { name: "Miel", amount: "1 cdita" }
        ]
    },
    {
        name: "Chilaquiles con Pollo (Rojos/Verdes)",
        category: "Poultry",
        icon: "fa-bowl-rice",
        cal: 530, fat: 22, prot: 28, carb: 55, purines: 85,
        status: "caution",
        tip: "MODERACIÓN. El pollo y la tortilla son seguros, pero la crema, el queso y la cocción de la salsa pueden sumar grasas. Pídelos con poca crema y pechuga de pollo desmenuzada (no piel) para mantener el riesgo bajo.",
        favourite: true,
        ingredients: [
            { name: "Totopos de tortilla", amount: "150g" },
            { name: "Pechuga de pollo deshebrada", amount: "100g" },
            { name: "Salsa roja/verde", amount: "200ml" },
            { name: "Crema ácida", amount: "2 cdas" },
            { name: "Queso fresco", amount: "30g" },
            { name: "Cebolla blanca", amount: "1/4 pieza" },
            { name: "Cilantro", amount: "al gusto" }
        ]
    },
    {
        name: "Hamburguesa Don Doblecarne",
        category: "Fast Food",
        icon: "fa-burger",
        cal: 850, fat: 45, prot: 54, carb: 48, purines: 180,
        status: "avoid",
        tip: "MUY ALTO RIESGO. Doble carne roja significa doble carga de purinas y grasas saturadas. Es una bomba para el riñón. Si tienes antojo, es mejor una hamburguesa sencilla de pollo o vegetariana. Evita acompañarla con cerveza.",
        favourite: true,
        ingredients: [
            { name: "Pan de hamburguesa", amount: "1 pieza" },
            { name: "Carne de res (2 carnes)", amount: "200g" },
            { name: "Queso amarillo", amount: "2 rebanadas" },
            { name: "Lechuga", amount: "2 hojas" },
            { name: "Tomate", amount: "2 rodajas" },
            { name: "Cebolla", amount: "2 anillos" },
            { name: "Mayonesa", amount: "1 cda" },
            { name: "Catsup", amount: "1 cda" },
            { name: "Mostaza", amount: "1 cdita" }
        ]
    },
    { name: "Vino Tinto (Copa 150ml)", category: "Drinks", icon: "fa-wine-glass", cal: 125, fat: 0, prot: 0, carb: 4, purines: 2, status: "caution", tip: "MEJOR OPCIÓN ALCOHÓLICA. El vino tinto tiene muy pocas purinas.", favourite: true },
    { name: "Vino Blanco (Copa 150ml)", category: "Drinks", icon: "fa-wine-glass-empty", cal: 121, fat: 0, prot: 0, carb: 4, purines: 2, status: "caution", tip: "MODERADO. Bajo en purinas, pero con azúcar.", favourite: true },
    { name: "Cerveza Indio (Botella 355ml)", category: "Drinks", icon: "fa-beer-mug-empty", cal: 150, fat: 0, prot: 1, carb: 14, purines: 35, status: "caution", tip: "RIESGO MODERADO. Cerveza oscura.", favourite: true },
    { name: "Cerveza Indio (Caguamón 1.18L)", category: "Drinks", icon: "fa-beer-mug-empty", cal: 510, fat: 0, prot: 4, carb: 46, purines: 120, status: "avoid", tip: "PELIGRO GOTA. Demasiado alcohol y levadura.", favourite: true },
    { name: "Miller High Life (940 ml)", category: "Drinks", icon: "fa-beer-mug-empty", cal: 373, fat: 0, prot: 2.7, carb: 32.3, purines: 110, status: "avoid", tip: "ALTO RIESGO. Cerveza Lager en gran volumen.", favourite: true },
    { name: "Cerveza XX Lager (Botella 355ml)", category: "Drinks", icon: "fa-beer-mug-empty", cal: 130, fat: 0, prot: 1, carb: 11, purines: 25, status: "caution", tip: "LIGERAMENTE MEJOR. Tipo Lager clara.", favourite: true },
    { name: "Cerveza XX Ambar (Botella 355ml)", category: "Drinks", icon: "fa-beer-mug-empty", cal: 145, fat: 0, prot: 1, carb: 13, purines: 32, status: "caution", tip: "ESTILO VIENA. Maltas tostadas.", favourite: true },
    { name: "Cerveza Victoria (Botella 355ml)", category: "Drinks", icon: "fa-beer-mug-empty", cal: 140, fat: 0, prot: 1, carb: 13, purines: 30, status: "caution", tip: "RIESGO MEDIO. Cerveza tipo Viena.", favourite: true },
    { name: "Cerveza Victoria (Caguama 940ml)", category: "Drinks", icon: "fa-beer-mug-empty", cal: 375, fat: 0, prot: 3, carb: 35, purines: 85, status: "avoid", tip: "ALTO RIESGO. Gran volumen satura el hígado.", favourite: true },
    { name: "Cerveza de Tarro / Michelada (1 Litro)", category: "Drinks", icon: "fa-martini-glass-citrus", cal: 450, fat: 0, prot: 3, carb: 45, purines: 110, status: "avoid", tip: "LA PEOR OPCIÓN. Exceso de purinas y sodio.", favourite: true },
    { name: "Whisky (Copa 45ml)", category: "Drinks", icon: "fa-martini-glass-empty", cal: 105, fat: 0, prot: 0, carb: 0, purines: 0, status: "caution", tip: "SIN PURINAS PERO CUIDADO. Destilados.", favourite: true },
    { name: "Tequila (Caballito 45ml)", category: "Drinks", icon: "fa-wine-bottle", cal: 97, fat: 0, prot: 0, carb: 0, purines: 0, status: "caution", tip: "OPCIÓN NEUTRA. Opción limpia si vas a beber.", favourite: true },
    { name: "Refresco de Cola (600ml)", category: "Drinks", icon: "fa-bottle-water", cal: 252, fat: 0, prot: 0, carb: 63, purines: 0, status: "avoid", tip: "ENEMIGO SILENCIOSO. Fructosa eleva el ácido úrico.", favourite: true },
    { name: "Agua de Jamaica (Sin Azúcar / 1 Vaso)", category: "Drinks", icon: "fa-glass-water", cal: 10, fat: 0, prot: 0, carb: 2, purines: 0, status: "safe", tip: "MUY RECOMENDADO. La jamaica es un diurético natural.", favourite: true },
    { name: "Jugo de Naranja (Natural 250ml)", category: "Drinks", icon: "fa-lemon", cal: 112, fat: 0, prot: 2, carb: 26, purines: 0, status: "caution", tip: "CUIDADO FRUCTOSA. El jugo concentra el azúcar.", favourite: true },
    { name: "Menudo / Pancita (Plato Grande)", category: "Meats", icon: "fa-bowl-rice", cal: 380, fat: 18, prot: 35, carb: 15, purines: 300, status: "avoid", tip: "PROHIBIDO EN CRISIS. Las vísceras son fuentes concentradas de purinas.", favourite: true, ingredients: [{ name: "Panza de res", amount: "200g" }, { name: "Caldo de res", amount: "400ml" }, { name: "Maíz pozolero", amount: "50g" }, { name: "Chile guajillo", amount: "3 piezas" }, { name: "Orégano", amount: "1 cdita" }, { name: "Limón", amount: "1 pieza" }, { name: "Cebolla", amount: "al gusto" }] },
    { name: "Hígado Encebollado (150g)", category: "Meats", icon: "fa-cow", cal: 260, fat: 10, prot: 28, carb: 12, purines: 350, status: "avoid", tip: "PELIGRO MÁXIMO. El hígado tiene la carga más alta de purinas.", favourite: true, ingredients: [{ name: "Hígado de res", amount: "150g" }, { name: "Cebolla blanca", amount: "1 pieza" }, { name: "Aceite", amount: "1 cda" }, { name: "Ajo", amount: "2 dientes" }, { name: "Sal y pimienta", amount: "al gusto" }] },
    { name: "Pozole Rojo de Cerdo (Plato)", category: "Meats", icon: "fa-bowl-rice", cal: 420, fat: 15, prot: 25, carb: 45, purines: 110, status: "caution", tip: "DEPENDE LA CARNE. El maíz pozolero es seguro.", favourite: true, ingredients: [{ name: "Carne de cerdo", amount: "120g" }, { name: "Maíz pozolero", amount: "100g" }, { name: "Chile guajillo", amount: "4 piezas" }, { name: "Lechuga", amount: "al gusto" }, { name: "Rábanos", amount: "3 piezas" }, { name: "Tostadas", amount: "2 piezas" }, { name: "Orégano", amount: "1 cdita" }] },
    { name: "Pechuga de Pollo Asada (150g)", category: "Poultry", icon: "fa-drumstick-bite", cal: 165, fat: 3.5, prot: 31, carb: 0, purines: 60, status: "safe", tip: "PROTEÍNA SEGURA. El pollo sin piel es moderado en purinas.", favourite: true },
    { name: "Salmón a la Plancha (150g)", category: "Seafood", icon: "fa-fish", cal: 310, fat: 18, prot: 34, carb: 0, purines: 110, status: "caution", tip: "BUENO CON MODERACIÓN. Tiene purinas moderadas.", favourite: true },
    { name: "Sardinas en Tomate (Lata)", category: "Seafood", icon: "fa-fish", cal: 220, fat: 15, prot: 20, carb: 2, purines: 300, status: "avoid", tip: "MUY ALTO EN PURINAS. Evitar sardinas y anchoas.", favourite: true },
    { name: "Frijoles de la Olla (1 Taza)", category: "Veggies", icon: "fa-leaf", cal: 230, fat: 1, prot: 15, carb: 40, purines: 60, status: "caution", tip: "MITO COMÚN. Tienen purinas vegetales.", favourite: true },
    { name: "Lentejas (Sopa 1 Taza)", category: "Veggies", icon: "fa-leaf", cal: 190, fat: 3, prot: 12, carb: 30, purines: 50, status: "safe", tip: "EXCELENTE FUENTE. Aportan fibra.", favourite: true },
    { name: "Ensalada César (Plato)", category: "Veggies", icon: "fa-leaf", cal: 350, fat: 25, prot: 8, carb: 10, purines: 20, status: "safe", tip: "CUIDADO ADEREZO. Lechuga y queso son seguros.", favourite: true, ingredients: [{ name: "Lechuga romana", amount: "150g" }, { name: "Queso parmesano", amount: "20g" }, { name: "Crutones", amount: "30g" }, { name: "Aderezo César", amount: "2 cdas" }, { name: "Pechuga de pollo", amount: "50g" }] },
    { name: "Pizza de Pepperoni (2 Rebanadas)", category: "Fast Food", icon: "fa-pizza-slice", cal: 600, fat: 28, prot: 24, carb: 65, purines: 60, status: "caution", tip: "GRASA Y HARINA. Pepperoni tiene purinas.", favourite: true, ingredients: [{ name: "Masa de pizza", amount: "150g" }, { name: "Salsa de tomate", amount: "50ml" }, { name: "Queso mozzarella", amount: "80g" }, { name: "Pepperoni", amount: "20 rebanadas" }, { name: "Orégano", amount: "al gusto" }] },
    { name: "Hot Dog (Sencillo)", category: "Fast Food", icon: "fa-hotdog", cal: 300, fat: 18, prot: 10, carb: 25, purines: 40, status: "caution", tip: "EMBUTIDOS. Salchichas procesadas.", favourite: true, ingredients: [{ name: "Pan de hot dog", amount: "1 pieza" }, { name: "Salchicha", amount: "1 pieza" }, { name: "Catsup", amount: "1 cda" }, { name: "Mostaza", amount: "1 cdita" }, { name: "Cebolla picada", amount: "1 cda" }] },
    { name: "Papaya Picada (1 Taza)", category: "Fruits", icon: "fa-apple-whole", cal: 60, fat: 0, prot: 1, carb: 15, purines: 0, status: "safe", tip: "ANTIINFLAMATORIO. Papaína ayuda digestión.", favourite: true },
    { name: "Cerezas (1 Taza)", category: "Fruits", icon: "fa-apple-whole", cal: 90, fat: 0, prot: 1, carb: 22, purines: 0, status: "safe", tip: "MEDICINA NATURAL. Reduce ácido úrico.", favourite: true },
    { name: "Café Americano (Taza 250ml)", category: "Drinks", icon: "fa-mug-hot", cal: 2, fat: 0, prot: 0, carb: 0, purines: 0, status: "safe", tip: "PROTECTOR. Café ayuda a disminuir ácido úrico.", favourite: true },
    { name: "Yogur Griego Natural (150g)", category: "Dairy", icon: "fa-cow", cal: 90, fat: 0, prot: 15, carb: 6, purines: 0, status: "safe", tip: "EXCELENTE FUENTE. Proteínas lácteas ayudan.", favourite: true },
    { name: "Atún Fresco (Medallón 150g)", category: "Seafood", icon: "fa-fish", cal: 180, fat: 2, prot: 35, carb: 0, purines: 180, status: "caution", tip: "MEJOR QUE LATA. Purinas pero sin sodio.", favourite: true },
    // --- MIS FAVORITOS (Manual Restore) ---
    { name: "Hot Cakes (Orden de 2 pzas)", category: "Others", icon: "fa-utensils", cal: 227, fat: 10, prot: 6, carb: 28, purines: 12, status: "safe", tip: "CUIDADO CON EL JARABE.", favourite: true, ingredients: [{ name: "Harina para hot cakes", amount: "80g" }, { name: "Huevo", amount: "1 pieza" }, { name: "Leche", amount: "100ml" }, { name: "Mantequilla", amount: "20g" }, { name: "Miel de maple", amount: "2 cdas" }] },
    { name: "Negra Modelo (Mega 1.2L)", category: "Drinks", icon: "fa-beer-mug-empty", cal: 581, fat: 0, prot: 5, carb: 53, purines: 140, status: "avoid", tip: "ALTO RIESGO GOTA.", favourite: true },
    { name: "Costillas de Cerdo (220g)", category: "Meats", icon: "fa-bone", cal: 638, fat: 46, prot: 52, carb: 0, purines: 264, status: "avoid", tip: "ALTO CONTENIDO GRASO.", favourite: true, ingredients: [{ name: "Costillas de cerdo", amount: "220g" }, { name: "Salsa BBQ", amount: "2 cdas" }, { name: "Ajo en polvo", amount: "1 cdita" }, { name: "Sal y pimienta", amount: "al gusto" }] },
    { name: "Tacos de Carnitas (Orden de 3)", category: "Fast Food", icon: "fa-utensils", cal: 760, fat: 42, prot: 48, carb: 45, purines: 250, status: "avoid", tip: "BOMBA PARA GOTA.", favourite: true, ingredients: [{ name: "Carnitas de cerdo", amount: "180g" }, { name: "Tortillas de maíz", amount: "3 piezas" }, { name: "Cilantro", amount: "al gusto" }, { name: "Cebolla picada", amount: "2 cdas" }, { name: "Limón", amount: "1 pieza" }, { name: "Salsa verde", amount: "2 cdas" }] },
    { name: "Pasta con Mejillones (350g)", category: "Seafood", icon: "fa-shrimp", cal: 440, fat: 12, prot: 24, carb: 58, purines: 145, status: "caution", tip: "MODERACIÓN.", favourite: true, ingredients: [{ name: "Pasta espagueti", amount: "150g" }, { name: "Mejillones", amount: "150g" }, { name: "Ajo", amount: "3 dientes" }, { name: "Vino blanco", amount: "50ml" }, { name: "Perejil", amount: "al gusto" }, { name: "Aceite de oliva", amount: "2 cdas" }] },
    { name: "Omelet de Claras, Queso y Espinaca", category: "Others", icon: "fa-egg", cal: 210, fat: 12, prot: 22, carb: 4, purines: 15, status: "safe", tip: "EXCELENTE PARA GOTA.", favourite: true, ingredients: [{ name: "Claras de huevo", amount: "4 piezas" }, { name: "Espinaca", amount: "50g" }, { name: "Queso panela", amount: "40g" }, { name: "Aceite de oliva", amount: "1 cdita" }, { name: "Sal", amount: "al gusto" }] },
    { name: "Albóndigas con Espagueti", category: "Meats", icon: "fa-utensils", cal: 535, fat: 22, prot: 26, carb: 58, purines: 125, status: "caution", tip: "CUIDADO CON LA CARNE.", favourite: true, ingredients: [{ name: "Carne molida de res", amount: "150g" }, { name: "Espagueti", amount: "120g" }, { name: "Salsa de tomate", amount: "150ml" }, { name: "Cebolla", amount: "1/4 pieza" }, { name: "Ajo", amount: "2 dientes" }, { name: "Pan molido", amount: "2 cdas" }, { name: "Huevo", amount: "1 pieza" }] },
    { name: "Arroz Blanco (250g)", category: "Others", icon: "fa-plate-wheat", cal: 325, fat: 1, prot: 7, carb: 70, purines: 15, status: "safe", tip: "ALIADO CONTRA LA GOTA.", favourite: true },
    { name: "Tortillas de Maíz (3 piezas)", category: "Others", icon: "fa-plate-wheat", cal: 190, fat: 2, prot: 5, carb: 39, purines: 10, status: "safe", tip: "OPCIÓN SEGURA.", favourite: true },
    { name: "Tostadas de Atún con Aguacate (2 pzas)", category: "Seafood", icon: "fa-shrimp", cal: 415, fat: 18, prot: 28, carb: 32, purines: 130, status: "caution", tip: "ATÚN CON MODERACIÓN.", favourite: true, ingredients: [{ name: "Tostadas de maíz", amount: "2 piezas" }, { name: "Atún en agua", amount: "1 lata" }, { name: "Aguacate", amount: "1/2 pieza" }, { name: "Mayonesa", amount: "1 cda" }, { name: "Limón", amount: "1 pieza" }, { name: "Cebolla morada", amount: "2 cdas" }] },
    { name: "Camarones a la Diabla (200g)", category: "Seafood", icon: "fa-shrimp", cal: 410, fat: 24, prot: 38, carb: 12, purines: 290, status: "avoid", tip: "PELIGROSO PARA GOTA.", favourite: true, ingredients: [{ name: "Camarones", amount: "200g" }, { name: "Chile guajillo", amount: "3 piezas" }, { name: "Chile de árbol", amount: "2 piezas" }, { name: "Ajo", amount: "3 dientes" }, { name: "Aceite", amount: "2 cdas" }, { name: "Cebolla", amount: "1/4 pieza" }] },
    { name: "Quesadilla Harina con Aguacate (1 pza)", category: "Fast Food", icon: "fa-utensils", cal: 340, fat: 19, prot: 12, carb: 28, purines: 18, status: "safe", tip: "OPCIÓN SEGURA.", favourite: true, ingredients: [{ name: "Tortilla de harina", amount: "1 pieza grande" }, { name: "Queso Oaxaca", amount: "50g" }, { name: "Aguacate", amount: "1/4 pieza" }, { name: "Crema", amount: "1 cda" }] },

    // --- CARNES Y AVES ---
    { name: "Pato (Con piel)", category: "Poultry", icon: "fa-dove", cal: 337, fat: 28, prot: 19, carb: 0, purines: 138, status: "caution", tip: "Keto friendly fat, but moderate purines." },
    { name: "Pato (Sin piel)", category: "Poultry", icon: "fa-dove", cal: 201, fat: 11, prot: 24, carb: 0, purines: 138, status: "caution", tip: "Leaner poultry option with moderate purines." },
    { name: "Ganso", category: "Poultry", icon: "fa-dove", cal: 371, fat: 33, prot: 16, carb: 0, purines: 165, status: "avoid", tip: "High purine levels make this risky for gout." },
    { name: "Codorniz (Con piel)", category: "Poultry", icon: "fa-dove", cal: 234, fat: 14, prot: 25, carb: 0, purines: 150, status: "caution", tip: "Small bird, moderate purine density." },
    { name: "Pavo (Pechuga)", category: "Poultry", icon: "fa-drumstick-bite", cal: 135, fat: 1, prot: 30, carb: 0, purines: 150, status: "caution", tip: "Lean protein, watch portion size for purines." },
    { name: "Pavo (Muslo)", category: "Poultry", icon: "fa-drumstick-bite", cal: 187, fat: 10, prot: 28, carb: 0, purines: 150, status: "caution", tip: "Dark meat turkey with moderate purines." },
    { name: "Carne de Venado", category: "Meats", icon: "fa-paw", cal: 158, fat: 3, prot: 30, carb: 0, purines: 140, status: "caution", tip: "Game meat is often high in purines." },
    { name: "Carne de Conejo", category: "Meats", icon: "fa-paw", cal: 173, fat: 8, prot: 25, carb: 0, purines: 132, status: "caution", tip: "Lean alternative with moderate purines." },
    { name: "Cordero (Chuleta)", category: "Meats", icon: "fa-bone", cal: 294, fat: 21, prot: 25, carb: 0, purines: 182, status: "avoid", tip: "Lamb chops are significantly high in purines." },
    { name: "Cordero (Pierna)", category: "Meats", icon: "fa-bone", cal: 200, fat: 10, prot: 28, carb: 0, purines: 140, status: "caution", tip: "Better choice than chops but still moderate." },
    { name: "Ternera (Lengua)", category: "Meats", icon: "fa-cow", cal: 284, fat: 22, prot: 19, carb: 0, purines: 160, status: "avoid", tip: "Very high purines found in organ meats." },
    { name: "Mollejas", category: "Meats", icon: "fa-cloud-meatball", cal: 240, fat: 18, prot: 18, carb: 0, purines: 990, status: "avoid", tip: "Extremely high purines! Avoid at all costs." },
    { name: "Cerdo (Lomo)", category: "Meats", icon: "fa-bone", cal: 242, fat: 14, prot: 27, carb: 0, purines: 120, status: "caution", tip: "Standard pork cut, moderate purine risk." },
    { name: "Jamón Ibérico (Bellota)", category: "Meats", icon: "fa-bone", cal: 350, fat: 25, prot: 30, carb: 0, purines: 125, status: "caution", tip: "Delicious Keto fat, but purines are moderate." },
    { name: "Salami", category: "Meats", icon: "fa-bone", cal: 336, fat: 26, prot: 22, carb: 2, purines: 120, status: "caution", tip: "Processed meat with moderate purines." },
    { name: "Pepperoni", category: "Meats", icon: "fa-bone", cal: 504, fat: 46, prot: 23, carb: 0, purines: 120, status: "caution", tip: "High fat, moderate purines." },
    { name: "Mortadela", category: "Meats", icon: "fa-bone", cal: 311, fat: 25, prot: 16, carb: 3, purines: 90, status: "caution", tip: "Lower purine index for a cold cut." },
    { name: "Salchicha Frankfurt", category: "Meats", icon: "fa-bone", cal: 290, fat: 26, prot: 12, carb: 2, purines: 90, status: "caution", tip: "Relatively low purines, watch for carbs." },
    { name: "Carne de Cabra", category: "Meats", icon: "fa-cow", cal: 143, fat: 3, prot: 27, carb: 0, purines: 120, status: "caution", tip: "Lean and moderate in purines." },
    { name: "Bisonte", category: "Meats", icon: "fa-cow", cal: 143, fat: 2, prot: 28, carb: 0, purines: 110, status: "caution", tip: "Very lean, moderate purines." },
    { name: "Pollo (Alitas con piel)", category: "Poultry", icon: "fa-drumstick-bite", cal: 290, fat: 19, prot: 27, carb: 0, purines: 110, status: "caution", tip: "Great for Keto, but watch the purines." },
    { name: "Gelatina (Sin sabor)", category: "Others", icon: "fa-fire", cal: 335, fat: 0, prot: 85, carb: 0, purines: 10, status: "safe", tip: "Safe and protein rich." },

    // --- PESCADOS Y MARISCOS ---
    { name: "Bacalao (Fresco)", category: "Seafood", icon: "fa-fish", cal: 82, fat: 0.7, prot: 18, carb: 0, purines: 109, status: "safe", tip: "Lean fish with safe purine levels." },
    { name: "Merluza", category: "Seafood", icon: "fa-fish", cal: 78, fat: 1.8, prot: 15, carb: 0, purines: 70, status: "safe", tip: "Excellent choice, low purine content." },
    { name: "Lenguado", category: "Seafood", icon: "fa-fish-fins", cal: 91, fat: 1.2, prot: 19, carb: 0, purines: 130, status: "caution", tip: "Moderate purines, enjoy in moderation." },
    { name: "Tilapia", category: "Seafood", icon: "fa-fish", cal: 96, fat: 1.7, prot: 20, carb: 0, purines: 100, status: "safe", tip: "Generally safe for gout patients." },
    { name: "Lubina", category: "Seafood", icon: "fa-fish", cal: 97, fat: 2, prot: 18, carb: 0, purines: 110, status: "caution", tip: "Moderate purine levels." },
    { name: "Dorada", category: "Seafood", icon: "fa-fish", cal: 115, fat: 4, prot: 19, carb: 0, purines: 120, status: "caution", tip: "Watch portion sizes due to moderate purines." },
    { name: "Trucha", category: "Seafood", icon: "fa-fish-fins", cal: 148, fat: 6.6, prot: 20, carb: 0, purines: 297, status: "avoid", tip: "Surprisingly high in purines, avoid if possible." },
    { name: "Caballa (Mackerel)", category: "Seafood", icon: "fa-fish", cal: 305, fat: 25, prot: 19, carb: 0, purines: 145, status: "caution", tip: "High Omega-3, but caution on purines." },
    { name: "Arenque (Herring)", category: "Seafood", icon: "fa-water", cal: 158, fat: 9, prot: 18, carb: 0, purines: 210, status: "avoid", tip: "Very high purines, avoid during flares." },
    { name: "Pez Espada", category: "Seafood", icon: "fa-fish-fins", cal: 144, fat: 6.7, prot: 19.8, carb: 0, purines: 130, status: "caution", tip: "Large fish with moderate purines." },
    { name: "Mero", category: "Seafood", icon: "fa-fish", cal: 92, fat: 1, prot: 19, carb: 0, purines: 80, status: "safe", tip: "Safe white fish option." },
    { name: "Bagre (Catfish)", category: "Seafood", icon: "fa-fish", cal: 95, fat: 2.9, prot: 16, carb: 0, purines: 100, status: "safe", tip: "Relatively low purines." },
    { name: "Rodaballo", category: "Seafood", icon: "fa-fish", cal: 95, fat: 3, prot: 16, carb: 0, purines: 120, status: "caution", tip: "Moderate purine fish." },
    { name: "Anguila", category: "Seafood", icon: "fa-fish", cal: 184, fat: 11, prot: 18, carb: 0, purines: 115, status: "caution", tip: "Fatty and moderate in purines." },
    { name: "Caviar", category: "Seafood", icon: "fa-gem", cal: 264, fat: 18, prot: 25, carb: 4, purines: 144, status: "caution", tip: "Luxury item with moderate purines." },
    { name: "Calamar", category: "Seafood", icon: "fa-shrimp", cal: 92, fat: 1.4, prot: 15.6, carb: 3, purines: 135, status: "caution", tip: "Moderate purines, watch for breading." },
    { name: "Pulpo", category: "Seafood", icon: "fa-shrimp", cal: 82, fat: 1, prot: 15, carb: 2.2, purines: 80, status: "safe", tip: "Octopus is generally lower in purines." },
    { name: "Mejillones", category: "Seafood", icon: "fa-shrimp", cal: 86, fat: 2.2, prot: 12, carb: 3.7, purines: 154, status: "avoid", tip: "Shellfish like mussels are high in purines." },
    { name: "Ostras", category: "Seafood", icon: "fa-shrimp", cal: 68, fat: 2.5, prot: 7, carb: 4, purines: 180, status: "avoid", tip: "Oysters are risky for gout flares." },
    { name: "Almejas", category: "Seafood", icon: "fa-shrimp", cal: 74, fat: 1, prot: 13, carb: 2.5, purines: 145, status: "caution", tip: "Moderate purines in clams." },
    { name: "Vieiras (Scallops)", category: "Seafood", icon: "fa-shrimp", cal: 88, fat: 0.8, prot: 17, carb: 2.4, purines: 136, status: "caution", tip: "Moderate purine levels." },
    { name: "Cangrejo", category: "Seafood", icon: "fa-shrimp", cal: 84, fat: 1, prot: 18, carb: 0, purines: 125, status: "caution", tip: "Moderate for gout, great for Keto." },
    { name: "Langosta", category: "Seafood", icon: "fa-shrimp", cal: 90, fat: 0.9, prot: 19, carb: 0, purines: 100, status: "safe", tip: "Surprisingly lower purines for a shellfish." },
    { name: "Langostinos", category: "Seafood", icon: "fa-shrimp", cal: 106, fat: 1.7, prot: 20, carb: 0.9, purines: 147, status: "caution", tip: "King prawns have moderate purines." },
    { name: "Surimi", category: "Seafood", icon: "fa-fish-fins", cal: 99, fat: 0.9, prot: 15, carb: 7, purines: 25, status: "caution", tip: "Low purines but watch the hidden carbs!" },
    { name: "Halibut", category: "Seafood", icon: "fa-fish", cal: 140, fat: 3, prot: 27, carb: 0, purines: 130, status: "caution", tip: "Moderate purines fish." },

    // --- VERDURAS Y HORTALIZAS ---
    { name: "Acelgas", category: "Veggies", icon: "fa-leaf", cal: 19, fat: 0.2, prot: 1.8, carb: 3.7, purines: 30, status: "safe", tip: "Safe and healthy green leafy veggie." },
    { name: "Alcachofa", category: "Veggies", icon: "fa-seedling", cal: 47, fat: 0.2, prot: 3.3, carb: 10.5, purines: 78, status: "caution", tip: "Moderate purines and slightly higher carbs." },
    { name: "Berenjena", category: "Veggies", icon: "fa-egg", cal: 25, fat: 0.2, prot: 1, carb: 6, purines: 10, status: "safe", tip: "Very safe for both Keto and gout." },
    { name: "Calabaza", category: "Veggies", icon: "fa-sun", cal: 26, fat: 0.1, prot: 1, carb: 6.5, purines: 20, status: "caution", tip: "Relatively safe, watch carbs on strict Keto." },
    { name: "Chucrut", category: "Veggies", icon: "fa-jar", cal: 19, fat: 0.1, prot: 0.9, carb: 4.3, purines: 15, status: "safe", tip: "Probiotic and safe for gout." },
    { name: "Coles de Bruselas", category: "Veggies", icon: "fa-tree", cal: 43, fat: 0.3, prot: 3.4, carb: 9, purines: 69, status: "safe", tip: "Generally safe vegetable." },
    { name: "Col Rizada (Kale)", category: "Veggies", icon: "fa-leaf", cal: 49, fat: 0.9, prot: 4.3, carb: 8.8, purines: 48, status: "safe", tip: "Superfood green, safe and nutrient rich." },
    { name: "Endibias", category: "Veggies", icon: "fa-clover", cal: 17, fat: 0.2, prot: 1.3, carb: 3.4, purines: 12, status: "safe", tip: "Excellent for salads, very low purine." },
    { name: "Hinojo", category: "Veggies", icon: "fa-seedling", cal: 31, fat: 0.2, prot: 1.2, carb: 7, purines: 14, status: "safe", tip: "Low purine vegetable." },
    { name: "Jengibre (Raíz)", category: "Veggies", icon: "fa-seedling", cal: 80, fat: 0.8, prot: 1.8, carb: 18, purines: 5, status: "safe", tip: "Safe to use as a flavoring." },
    { name: "Nabos", category: "Veggies", icon: "fa-circle", cal: 28, fat: 0.1, prot: 0.9, carb: 6.4, purines: 10, status: "safe", tip: "Safe root vegetable alternative." },
    { name: "Pepinillos", category: "Veggies", icon: "fa-pepper-hot", cal: 11, fat: 0.2, prot: 0.3, carb: 2.3, purines: 5, status: "safe", tip: "Low calorie and safe snack." },
    { name: "Puerro", category: "Veggies", icon: "fa-wheat-awn", cal: 61, fat: 0.3, prot: 1.5, carb: 14, purines: 74, status: "caution", tip: "Higher carb count for a veggie." },
    { name: "Rábanos", category: "Veggies", icon: "fa-circle-notch", cal: 16, fat: 0.1, prot: 0.7, carb: 3.4, purines: 15, status: "safe", tip: "Crisp and safe." },
    { name: "Remolacha", category: "Veggies", icon: "fa-heart", cal: 43, fat: 0.2, prot: 1.6, carb: 9.6, purines: 20, status: "avoid", tip: "High sugar content is risky for Keto." },
    { name: "Rúcula", category: "Veggies", icon: "fa-leaf", cal: 25, fat: 0.7, prot: 2.6, carb: 3.7, purines: 20, status: "safe", tip: "Peppery green, completely safe." },
    { name: "Setas Shiitake", category: "Veggies", icon: "fa-cloud-meatball", cal: 34, fat: 0.5, prot: 2.2, carb: 6.8, purines: 150, status: "caution", tip: "Mushrooms contain moderate purines." },
    { name: "Zanahoria", category: "Veggies", icon: "fa-carrot", cal: 41, fat: 0.2, prot: 0.9, carb: 9.6, purines: 17, status: "caution", tip: "Watch carb count." },
    { name: "Papa (Cocida)", category: "Veggies", icon: "fa-circle", cal: 87, fat: 0.1, prot: 1.9, carb: 20, purines: 20, status: "avoid", tip: "Too high in starch/carbs." },
    { name: "Maíz", category: "Veggies", icon: "fa-wheat-awn", cal: 96, fat: 1.5, prot: 3.4, carb: 21, purines: 40, status: "avoid", tip: "Avoid on Keto starch limits." },
    { name: "Guisantes", category: "Veggies", icon: "fa-circle-dot", cal: 81, fat: 0.4, prot: 5.4, carb: 14, purines: 80, status: "avoid", tip: "High carb legume." },
    { name: "Algas Nori", category: "Veggies", icon: "fa-clover", cal: 35, fat: 0.3, prot: 5.8, carb: 5, purines: 500, status: "avoid", tip: "DANGEROUS purge risk! Too high in purines." },
    { name: "Brotes de Soja", category: "Veggies", icon: "fa-seedling", cal: 30, fat: 0.2, prot: 3, carb: 6, purines: 30, status: "safe", tip: "Safe crunchy veggie." },
    { name: "Palmitos", category: "Veggies", icon: "fa-tree", cal: 28, fat: 0.6, prot: 2.5, carb: 4.6, purines: 15, status: "safe", tip: "Low carb and safe." },
    { name: "Tomate Seco", category: "Veggies", icon: "fa-sun", cal: 258, fat: 3, prot: 14, carb: 55, purines: 20, status: "avoid", tip: "Very high carb density." },

    // --- LÁCTEOS Y ALTERNATIVAS ---
    { name: "Leche Entera", category: "Dairy", icon: "fa-cow", cal: 61, fat: 3.3, prot: 3.2, carb: 4.8, purines: 0, status: "caution", tip: "Purine safe, but watch the lactose (carbs) for Keto." },
    { name: "Leche de Almendras", category: "Dairy", icon: "fa-bottle-droplet", cal: 13, fat: 1.1, prot: 0.5, carb: 0.1, purines: 0, status: "safe", tip: "Perfect Keto milk substitute. Gout safe." },
    { name: "Leche de Coco", category: "Dairy", icon: "fa-bottle-water", cal: 197, fat: 21, prot: 2, carb: 2.8, purines: 0, status: "safe", tip: "High healthy fats, zero purines." },
    { name: "Queso Brie", category: "Dairy", icon: "fa-cheese", cal: 334, fat: 28, prot: 21, carb: 0.5, purines: 8, status: "safe", tip: "Excellent for Keto, very low purine." },
    { name: "Queso Roquefort", category: "Dairy", icon: "fa-cheese", cal: 369, fat: 31, prot: 22, carb: 2, purines: 10, status: "safe", tip: "Blue cheese is safe and Keto-gold." },
    { name: "Queso Feta", category: "Dairy", icon: "fa-cheese", cal: 264, fat: 21, prot: 14, carb: 4, purines: 10, status: "safe", tip: "Safe dairy option." },
    { name: "Queso Gouda", category: "Dairy", icon: "fa-cheese", cal: 356, fat: 27, prot: 25, carb: 2, purines: 10, status: "safe", tip: "Great high fat cheese." },
    { name: "Queso Cottage", category: "Dairy", icon: "fa-cheese", cal: 98, fat: 4.3, prot: 11, carb: 3.4, purines: 8, status: "safe", tip: "Safe protein source." },
    { name: "Queso Mascarpone", category: "Dairy", icon: "fa-cheese", cal: 455, fat: 47, prot: 3.6, carb: 4, purines: 0, status: "safe", tip: "High fat, zero purine." },
    { name: "Queso de Cabra", category: "Dairy", icon: "fa-cheese", cal: 364, fat: 30, prot: 22, carb: 0.1, purines: 10, status: "safe", tip: "Very low carb, very safe." },
    { name: "Mantequilla Ghee", category: "Dairy", icon: "fa-droplet", cal: 900, fat: 100, prot: 0, carb: 0, purines: 0, status: "safe", tip: "Pure fat, zero purine, infinite Keto fuel." },

    // --- FRUTAS ---
    { name: "Moras (Blackberries)", category: "Fruits", icon: "fa-circle-nodes", cal: 43, fat: 0.5, prot: 1.4, carb: 9.6, purines: 15, status: "safe", tip: "The best fruit for Keto/Gout. Low carb/low purine." },
    { name: "Cerezas Frescas", category: "Fruits", icon: "fa-heart", cal: 50, fat: 0.3, prot: 1, carb: 12, purines: 10, status: "caution", tip: "Helps lower uric acid, but watch the carbs." },
    { name: "Kiwi", category: "Fruits", icon: "fa-apple-whole", cal: 61, fat: 0.5, prot: 1.1, carb: 15, purines: 19, status: "avoid", tip: "Too high in sugar for Keto." },
    { name: "Mango", category: "Fruits", icon: "fa-sun", cal: 60, fat: 0.4, prot: 0.8, carb: 15, purines: 15, status: "avoid", tip: "Sugary fruit, avoid on strict diets." },
    { name: "Aceitunas Negras", category: "Fruits", icon: "fa-circle-dot", cal: 115, fat: 11, prot: 0.8, carb: 6, purines: 0, status: "safe", tip: "Technically a fruit, safe and fatty." },
    { name: "Ruibarbo", category: "Fruits", icon: "fa-leaf", cal: 21, fat: 0.2, prot: 0.9, carb: 4.5, purines: 10, status: "safe", tip: "Great low carb fruit alternative." },

    // --- FRUTOS SECOS Y SEMILLAS ---
    { name: "Avellanas", category: "Nuts", icon: "fa-seedling", cal: 628, fat: 61, prot: 15, carb: 17, purines: 37, status: "safe", tip: "Keto favorable, safe purines." },
    { name: "Anacardos (Merey)", category: "Nuts", icon: "fa-wheat-awn", cal: 553, fat: 44, prot: 18, carb: 30, purines: 50, status: "caution", tip: "Higher carb count for nuts." },
    { name: "Piñones", category: "Nuts", icon: "fa-star", cal: 673, fat: 68, prot: 14, carb: 13, purines: 0, status: "safe", tip: "Pure fat and zero purine." },
    { name: "Semillas de Lino", category: "Nuts", icon: "fa-dna", cal: 534, fat: 42, prot: 18, carb: 29, purines: 28, status: "safe", tip: "Great for fiber and safe." },
    { name: "Crema de Almendras", category: "Nuts", icon: "fa-jar-wheat", cal: 614, fat: 56, prot: 21, carb: 19, purines: 37, status: "safe", tip: "Safe Keto spread." },
    { name: "Harina de Almendra", category: "Nuts", icon: "fa-wheat-awn", cal: 571, fat: 50, prot: 21, carb: 22, purines: 37, status: "safe", tip: "Prime Keto baking staple." },

    // --- ORIGINAL / SPECIFIC ITEMS ---
    { name: "Salmon", category: "Seafood", icon: "fa-fish", cal: 208, fat: 13, prot: 20, carb: 0, purines: 150, status: "caution", tip: "Healthy Omega-3s." },
    { name: "Spinach", category: "Veggies", icon: "fa-leaf", cal: 23, fat: 0.4, prot: 2.9, carb: 1.4, purines: 57, status: "safe", tip: "Leafy green gold." },
    { name: "Beef Liver", category: "Meats", icon: "fa-cloud-meatball", cal: 175, fat: 5, prot: 27, carb: 3.8, purines: 554, status: "avoid", tip: "High purine danger." },
    { name: "Macadamia", category: "Nuts", icon: "fa-seedling", cal: 718, fat: 76, prot: 8, carb: 1.5, purines: 0, status: "safe", tip: "Keto King." },
    { name: "Beer", category: "Drinks", icon: "fa-beer-mug-empty", cal: 43, fat: 0, prot: 0.5, carb: 3.6, purines: 0, status: "avoid", tip: "Purine and Carb bomb." },
    { name: "Cauliflower", category: "Veggies", icon: "fa-tree", cal: 25, fat: 0.3, prot: 1.9, carb: 3, purines: 51, status: "safe", tip: "Keto staple." },
    // --- AUREUS ORIGINALS ---
    { name: "Cinnamon Roll (AUREUS Original)", category: "Originals", icon: "fa-crown", cal: 450, fat: 12, prot: 8, carb: 42, purines: 10, status: "safe", tip: "Nuestro Rol de Canela especial, bajo en purinas." },
    { name: "AUREUS Burger XL", category: "Originals", icon: "fa-gem", cal: 680, fat: 32, prot: 45, carb: 12, purines: 120, status: "caution", tip: "Versión controlada de hamburguesa, carne magra." },
    { name: "Ensalada AUREUS Detox", category: "Originals", icon: "fa-flask", cal: 320, fat: 15, prot: 12, carb: 18, purines: 25, status: "safe", tip: "Combinación ideal de hojas verdes y grasas buenas." },
    { name: "Smoothie AUREUS Power", category: "Originals", icon: "fa-blender", cal: 210, fat: 5, prot: 18, carb: 14, purines: 15, status: "safe", tip: "Batido de proteína con frutos rojos y espinaca." },
    { name: "Bowl AUREUS Ancestral", category: "Originals", icon: "fa-dna", cal: 480, fat: 22, prot: 30, carb: 35, purines: 65, status: "safe", tip: "Base de quinoa con salmón y vegetales al vapor." }
];
